inherit_gem:
  jekyll: .rubocop.yml

Metrics/LineLength:
  Exclude:
    - spec/**/*
    - jekyll-seo-tag.gemspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

AllCops:
  Exclude:
    - vendor/**/*
